src/FoodMaster.WebSite/Areas/Account/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

using FoodMaster.WebSite.Abstraction.Services;
using FoodMaster.WebSite.Domain;
using FoodMaster.WebSite.Filters;
using FoodMaster.WebSite.Models;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodMaster.WebSite.Areas.Account.Pages
{
    [ServiceFilter(typeof(WriteToDiskFilterAttribute))]
    [BindProperties]
    public class LoginModel : PageModel
    {
        private readonly IUsersService usersService;

        public LoginModel(IUsersService usersService)
        {
            this.usersService = usersService;
        }

        public GuestCredentials GuestCredentials { get; set; }


        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }

            var userId = Guid.NewGuid().ToString();
            var assignedRole = Roles.Guest.ToString();

            var claims = new Claim[]
            {
                new Claim(ClaimTypes.NameIdentifier, userId),
                new Claim(ClaimTypes.Name, GuestCredentials.FullName),
                new Claim(ClaimTypes.DateOfBirth, GuestCredentials.BirthDate.ToString()),
                new Claim(ClaimTypes.Role, assignedRole)
            };

            var user = new User
            {
                Id = userId,
                UserName = userId,
                FullName = GuestCredentials.FullName,
                BirthDate = GuestCredentials.BirthDate,
                Claims = new List<Claim>(claims),
                Role = assignedRole
            };
            
            usersService.Create(user);

            await HttpContext.SignInAsync(
                new ClaimsPrincipal(
                    new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme)));

            return RedirectToPagePermanent("Index");
        }


        public async Task<IActionResult> OnGetSignOutAsync()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Unauthorized();
            }

            var user = usersService.Get(u => u.Id == User.FindFirst(ClaimTypes.NameIdentifier).Value);

            if (user.Role.Equals(Roles.Guest.ToString()))
            {
                usersService.Delete(user);
            }

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToPage();
        }
    }
}

src/FoodMaster.WebSite/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodMaster</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand navbar-expand-sm" asp-area="" asp-page="/Index">
                    <img src="~/images/taco_64px.png" alt="FoodMaster" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-nav navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity?.IsAuthenticated == false)
                        {
                        <li class="nav-item">
                            <a class="nav-link" asp-page="AuthenticatePage">Login</a>
                        </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <form asp-area="Account" asp-page="AuthenticatePage" asp-page-handler="SignOut" id="signout-form">
                               <a class="nav-link" id="signout" onclick="signout()">Sign Out</a>
                            </form>
                        </li>
                        }
                    </ul>
                </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Redhouane Sobaihi &copy; @DateTime.Now.Year - FoodMaster
        </div>
    </footer>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>